// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5k7_l5GPufoAYPd6kMuE6DU2yq1tmtKQ',
    appId: '1:540013854762:web:066b0b944866dd135b4353',
    messagingSenderId: '540013854762',
    projectId: 'minimal-social-app-e8086',
    authDomain: 'minimal-social-app-e8086.firebaseapp.com',
    storageBucket: 'minimal-social-app-e8086.appspot.com',
    measurementId: 'G-DE0XJ0S2G6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB30W1A9fQS1t6Bn7eDX1eHL3Hxe5K1n6c',
    appId: '1:540013854762:android:b09589018d4791ca5b4353',
    messagingSenderId: '540013854762',
    projectId: 'minimal-social-app-e8086',
    storageBucket: 'minimal-social-app-e8086.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC74XCxYGPPX0H9bSP00Xu131Sk8hiG2Vs',
    appId: '1:540013854762:ios:9226efd589e664835b4353',
    messagingSenderId: '540013854762',
    projectId: 'minimal-social-app-e8086',
    storageBucket: 'minimal-social-app-e8086.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC74XCxYGPPX0H9bSP00Xu131Sk8hiG2Vs',
    appId: '1:540013854762:ios:80eae5ba940e191f5b4353',
    messagingSenderId: '540013854762',
    projectId: 'minimal-social-app-e8086',
    storageBucket: 'minimal-social-app-e8086.appspot.com',
    iosBundleId: 'com.example.socialMediaApp.RunnerTests',
  );
}
